### ISSUE TITLE
Arrow functions not being treated as functions inside of a class

### ISSUE THREAD

**Issue by illumincrotty** [heavenshell/ts-lehre#233]
Build Number: 
Lehre 1.4.0

Environment: 
Node 16.5.0  x64
pnpm 6.13.0
Typescript 4.5.0-dev

Description: 
Arrow functions inside of classes use generatePropertyDoc when they ought to use generateFunctionDoc

Reproduction:  
[minimal reproduction example](https://github.com/illumincrotty/lehre-nesting-minimal)

Expected result: 
arrow functions inside of classes have function documentation

**Comment by heavenshell** [comment]
Thank you for reporting.

So, you meant

```typescript
class Foo {
  method = (arg1: number) => {}
}
```

should be

```typescript
/**
 * Foo.
 */
class Foo {
  /**
   * method.
   *
   * @param {number} arg1
   */
  method = (arg1: number) => {}
}
```

like this?

**Comment by illumincrotty** [comment]
That exactly!

**Comment by heavenshell** [comment]
Thanks. I'll fix this.

**Comment by heavenshell** [comment]
@illumincrotty I've released v1.5.0. Please check it ☺️

**Comment by heavenshell** [comment]
```typescript
class Bar {
  props: number
  props2 = 'foo'
  render = (arg1: string): string => {
  }
  foo = (arg2: number) => {
  }
}

```

```
 cat ~/Downloads/sample.ts | ts-node src/cli.ts --stdin --parser=ts      
/**
 * Bar.
 */
class Bar {
  /**
   * @type {number}
   */
  props: number
  /**
   * @type {}
   */
  props2 = 'foo'
  /**
   * render.
   *
   * @param {string} arg1
   * @returns {string}
   */
  render = (arg1: string): string => {
  }
  /**
   * foo.
   *
   * @param {number} arg2
   */
  foo = (arg2: number) => {
  }
}
```

**Comment by illumincrotty** [comment]
I gave 1.5.0 a try and its working great now. Thanks!

**Comment by illumincrotty** [comment]
Would you mind adding the same change to interfaces? Interfaces are still treating arrow functions as if they are variable properties

**Comment by heavenshell** [comment]
What kind of change do you want.
Could you show me more details?
